[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc = "0.8.27"
fs_permissions = [{ access = "read", path = "./out" }]

[rpc_endpoints]
bartio = "https://bartio.rpc.berachain.com/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
